In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
import pickle
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 50)

from IdealDataInterface import IdealDataInterface
from IdealMetadataInterface import IdealMetadataInterface

### Specify the folder where your sensor data is

In [3]:
folder_path = 'D:\Documents\MSc Project\IDEAL Data\sensordata'
ideal = IdealDataInterface(folder_path)

Found entries for 1592 sensor readings.

In [4]:
metadatadir='D:\Documents\MSc Project\IDEAL Data\metadata_and_surveys\metadata'

                                                                                                                                            
mdi = IdealMetadataInterface(metadatadir)

Loading data from combined mains

In [ ]:
mains_data = ideal.view(category='electric-mains')

In [ ]:
mains_data

Loading metadata

In [8]:
md = mdi.metadata.homes['home']
md[['starttime','starttime_enhanced','endtime']] = md[['starttime','starttime_enhanced','endtime']].apply(pd.to_datetime, format='%d/%m/%Y %H:%M')
md

,homeid,install_type,location,residents,starttime,starttime_enhanced,endtime,cohortid,income_band,study_class,...,urban_rural_name,build_era,new_build_year,smart_monitors,smart_automation,occupied_days,occupied_nights,entry_floor,outdoor_space,outdoor_drying
0,47,standard,Edinburgh,2,2016-08-10 00:00:00,NaT,2017-05-08 09:00:00,treatment_20170315,Missing,treatment,...,Large Urban Areas,1900-1918,NaN,Don't own,Don't own,2,7,3rd,No,NaN
1,59,standard,Edinburgh,2,2016-10-06 00:00:00,NaT,2018-01-28 07:56:00,control_20170315,"£90,000 or more",control,...,Large Urban Areas,1900-1918,NaN,Don't own,Don't own,3,7,Ground,Yes - shared with neighbours,Yes
2,61,enhanced,Edinburgh,2,2016-10-06 00:00:00,2016-11-17,2017-10-19 07:00:00,enhanced_20170213,"£48,600 to £53,999",enhanced,...,Large Urban Areas,1919-1930,NaN,Don't own,Don't own,2,7,Ground,Yes - shared with neighbours,Yes
3,62,enhanced,Edinburgh,2,2016-08-26 00:00:00,2016-10-11,2018-06-30 22:59:00,enhanced_20170213,"£43,200 to £48,599",enhanced,...,Large Urban Areas,1850-1899,NaN,Don't own,Don't own,1,7,2nd,Yes - shared with neighbours,Yes
4,64,standard,Edinburgh,4,2016-10-20 00:00:00,NaT,2018-06-30 22:59:00,treatment_20170315,"£66,000 to £77,999",treatment,...,Large Urban Areas,Before 1850,NaN,Don't own,Don't own,6,7,1st,Yes - shared with neighbours,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,331,standard,Fife,2,2018-04-12 11:57:00,NaT,2018-06-30 22:59:00,treatment_20180514,"£54,000 to £65,999",treatment,...,Other Urban Areas,1965-1980,NaN,Don't own,Don't own,7,7,Ground,Yes - private,Yes
251,332,standard,Edinburgh,1,2018-04-19 09:14:00,NaT,2018-06-30 22:59:00,treatment_20180514,"£32,400 to £37,799",treatment,...,Large Urban Areas,1919-1930,NaN,Don't own,Don't own,2,7,Ground,Yes - private,Yes
252,334,standard,Edinburgh,5,2018-04-30 07:14:00,NaT,2018-06-30 22:59:00,control_20180514,"less than £10,800",control,...,Large Urban Areas,1850-1899,NaN,Don't own,Don't own,4,7,Ground,Yes - shared with neighbours,Yes
253,335,standard,EastLothian,4,2018-04-30 13:42:00,NaT,2018-06-30 22:59:00,treatment_20180514,"£78,000 to £89,999",treatment,...,Other Urban Areas,1991-1995,NaN,Don't own,Don't own,2,7,Ground,Yes - private,Yes
254,333,standard,Edinburgh,3,2018-04-30 07:27:00,NaT,2018-06-30 22:59:00,control_20180514,"£54,000 to £65,999",control,...,Large Urban Areas,Before 1850,NaN,Don't own,Don't own,2,7,1st,Yes - private,Yes

Reduce the dataset to only those records with a year or mores worth of readings

In [9]:
datecheck = md[['homeid', 'starttime','endtime']]
datecheck['days'] = (datecheck['endtime'] - datecheck['starttime']).dt.days
datecheck

<ipython-input-9-cdd4ceda43d6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  datecheck['days'] = (datecheck['endtime'] - datecheck['starttime']).dt.days

     homeid           starttime             endtime  days
0        47 2016-08-10 00:00:00 2017-05-08 09:00:00   271
1        59 2016-10-06 00:00:00 2018-01-28 07:56:00   479
2        61 2016-10-06 00:00:00 2017-10-19 07:00:00   378
3        62 2016-08-26 00:00:00 2018-06-30 22:59:00   673
4        64 2016-10-20 00:00:00 2018-06-30 22:59:00   618
..      ...                 ...                 ...   ...
250     331 2018-04-12 11:57:00 2018-06-30 22:59:00    79
251     332 2018-04-19 09:14:00 2018-06-30 22:59:00    72
252     334 2018-04-30 07:14:00 2018-06-30 22:59:00    61
253     335 2018-04-30 13:42:00 2018-06-30 22:59:00    61
254     333 2018-04-30 07:27:00 2018-06-30 22:59:00    61

[255 rows x 4 columns]

In [10]:
year_or_more_df = datecheck[datecheck.days >= 365]
year_or_more_df

    homeid           starttime             endtime  days
1       59 2016-10-06 00:00:00 2018-01-28 07:56:00   479
2       61 2016-10-06 00:00:00 2017-10-19 07:00:00   378
3       62 2016-08-26 00:00:00 2018-06-30 22:59:00   673
4       64 2016-10-20 00:00:00 2018-06-30 22:59:00   618
5       63 2016-10-28 00:00:00 2018-06-30 22:59:00   610
..     ...                 ...                 ...   ...
62     133 2017-06-27 12:35:00 2018-06-30 22:59:00   368
63     134 2017-06-28 07:30:00 2018-06-30 22:59:00   367
65     135 2017-06-28 10:44:00 2018-06-30 22:59:00   367
66     128 2017-06-22 09:25:00 2018-06-30 22:59:00   373
97     167 2016-08-24 01:00:00 2018-06-14 08:30:00   659

[60 rows x 4 columns]

In [11]:
year_or_more_df.size

240

In [12]:
sample_homeids = year_or_more_df.homeid.to_numpy()
sample_homeids

array([ 59,  61,  62,  64,  63,  65,  67,  66,  68,  70,  73,  69,  75,
        72,  74,  78,  71,  77,  76,  79,  81,  88,  86,  83,  82,  85,
        89,  90,  92,  93,  98,  94,  96,  97, 100, 101,  99, 102, 107,
       106, 109, 110, 105, 114, 115, 116, 118, 121, 126, 129, 117, 119,
       122, 123, 125, 133, 134, 135, 128, 167], dtype=int64)

Function to read in relevant house ids

In [13]:
def load_readings(houseid):
    'Funciton to load in data for the house electricity use and resample to 1 hour'
    
    data = ideal.get(homeid=houseid, subtype='electric-combined')[0]['readings']
    
    df = pd.DataFrame(data).resample('H').agg(lambda x: sum(x/3600)/1000)
    
    return df

In [14]:
def load_data(arr):
    'Function to load in all readings of relevant homes'
    
    data = {}
    
    for i in arr:
        
        print('i: ', i)

        data[i] = load_readings(int(i))
        
    return data

In [ ]:
test_arr = np.array([59])
type(test_arr)

In [15]:
data = load_data(sample_homeids)

i:  59
i:  61
i:  62
i:  64
i:  63
i:  65
i:  67
i:  66
i:  68
i:  70
i:  73
i:  69
i:  75
i:  72
i:  74
i:  78
i:  71
i:  77
i:  76
i:  79
i:  81
i:  88
i:  86
i:  83
i:  82
i:  85
i:  89
i:  90
i:  92
i:  93
i:  98
i:  94
i:  96
i:  97
i:  100
i:  101
i:  99
i:  102
i:  107
i:  106
i:  109
i:  110
i:  105
i:  114
i:  115
i:  116
i:  118
i:  121
i:  126
i:  129
i:  117
i:  119
i:  122
i:  123
i:  125
i:  133
i:  134
i:  135
i:  128
i:  167

In [16]:
data

{59:                      electric-combined
 time
 2016-10-06 09:00:00           0.135684
 2016-10-06 10:00:00           0.177023
 2016-10-06 11:00:00           0.587103
 2016-10-06 12:00:00           0.220286
 2016-10-06 13:00:00           0.143367
 ...                                ...
 2018-01-28 03:00:00           0.091263
 2018-01-28 04:00:00           0.077921
 2018-01-28 05:00:00           0.065573
 2018-01-28 06:00:00           0.061346
 2018-01-28 07:00:00           0.055258

 [11495 rows x 1 columns],
 61:                      electric-combined
 time
 2016-10-06 12:00:00           0.094648
 2016-10-06 13:00:00           0.215611
 2016-10-06 14:00:00           0.289798
 2016-10-06 15:00:00           0.078180
 2016-10-06 16:00:00           0.074056
 ...                                ...
 2017-10-19 02:00:00           0.054154
 2017-10-19 03:00:00           0.000000
 2017-10-19 04:00:00           0.174604
 2017-10-19 05:00:00           0.214912
 2017-10-19 06:00:00           0.285726

 [9067 rows x 1 columns],
 62:                      electric-combined
 time
 2016-08-26 09:00:00           0.015059
 2016-08-26 10:00:00           0.121332
 2016-08-26 11:00:00           0.272292
 2016-08-26 12:00:00           0.492458
 2016-08-26 13:00:00           0.541853
 ...                                ...
 2018-06-30 19:00:00           0.277313
 2018-06-30 20:00:00           0.221928
 2018-06-30 21:00:00           0.172749
 2018-06-30 22:00:00           0.163090
 2018-06-30 23:00:00           0.208072

 [16167 rows x 1 columns],
 64:                      electric-combined
 time
 2016-10-20 09:00:00           0.522627
 2016-10-20 10:00:00           0.257400
 2016-10-20 11:00:00           0.269574
 2016-10-20 12:00:00           0.167766
 2016-10-20 13:00:00           0.239859
 ...                                ...
 2018-06-30 19:00:00           0.209326
 2018-06-30 20:00:00           0.240710
 2018-06-30 21:00:00           0.149671
 2018-06-30 22:00:00           0.146466
 2018-06-30 23:00:00           0.146645

 [14847 rows x 1 columns],
 63:                      electric-combined
 time
 2016-10-28 13:00:00           0.233777
 2016-10-28 14:00:00           0.267790
 2016-10-28 15:00:00           0.243871
 2016-10-28 16:00:00           0.304959
 2016-10-28 17:00:00           0.178849
 ...                                ...
 2018-06-30 19:00:00           0.985282
 2018-06-30 20:00:00           0.474631
 2018-06-30 21:00:00           0.811795
 2018-06-30 22:00:00           0.697529
 2018-06-30 23:00:00           0.213694

 [14651 rows x 1 columns],
 65:                      electric-combined
 time
 2016-11-09 14:00:00           0.278701
 2016-11-09 15:00:00           0.655004
 2016-11-09 16:00:00           0.758222
 2016-11-09 17:00:00           0.482512
 2016-11-09 18:00:00           0.384276
 ...                                ...
 2018-06-30 19:00:00           1.085911
 2018-06-30 20:00:00           1.106592
 2018-06-30 21:00:00           0.475310
 2018-06-30 22:00:00           0.642547
 2018-06-30 23:00:00           1.436469

 [14362 rows x 1 columns],
 67:                      electric-combined
 time
 2016-12-05 10:00:00           0.146658
 2016-12-05 11:00:00           0.280612
 2016-12-05 12:00:00           1.850291
 2016-12-05 13:00:00           0.705230
 2016-12-05 14:00:00           0.356030
 ...                                ...
 2018-06-21 03:00:00           0.331729
 2018-06-21 04:00:00           0.279045
 2018-06-21 05:00:00           0.390250
 2018-06-21 06:00:00           0.183946
 2018-06-21 07:00:00           0.039205

 [13510 rows x 1 columns],
 66:                      electric-combined
 time
 2016-11-23 10:00:00           0.184380
 2016-11-23 11:00:00           0.291661
 2016-11-23 12:00:00           0.197729
 2016-11-23 13:00:00           0.164545
 2016-11-23 14:00:00           0.203255
 ...                                ...
 2018-06-30 19:00:00           0.185291
 2018-06-30 20:00:00           0.107985
 2018-06-30 21:00:00           0.138704
 2018-06-30 22:00:00           0.081042
 2018-06-30 23:00:00           0.127372

 [14030 rows x 1 columns],
 68:                      electric-combined
 time
 2016-11-24 10:00:00           0.334034
 2016-11-24 11:00:00           0.407336
 2016-11-24 12:00:00           0.367414
 2016-11-24 13:00:00           0.366431
 2016-11-24 14:00:00           0.280700
 ...                                ...
 2018-06-30 19:00:00           0.355875
 2018-06-30 20:00:00           0.475956
 2018-06-30 21:00:00           0.427902
 2018-06-30 22:00:00           0.305705
 2018-06-30 23:00:00           0.219891

 [14006 rows x 1 columns],
 70:                      electric-combined
 time
 2016-12-07 14:00:00           0.344933
 2016-12-07 15:00:00           0.622617
 2016-12-07 16:00:00           0.098561
 2016-12-07 17:00:00           0.117364
 2016-12-07 18:00:00           0.542610
 ...                                ...
 2018-06-30 19:00:00           0.090776
 2018-06-30 20:00:00           0.434951
 2018-06-30 21:00:00           0.766399
 2018-06-30 22:00:00           1.148596
 2018-06-30 23:00:00           0.919819

 [13690 rows x 1 columns],
 73:                      electric-combined
 time
 2016-12-15 14:00:00           0.000955
 2016-12-15 15:00:00           0.143301
 2016-12-15 16:00:00           0.069580
 2016-12-15 17:00:00           0.132617
 2016-12-15 18:00:00           0.267561
 ...                                ...
 2018-06-24 09:00:00           0.082796
 2018-06-24 10:00:00           0.150518
 2018-06-24 11:00:00           0.171477
 2018-06-24 12:00:00           0.733012
 2018-06-24 13:00:00           0.141034

 [13344 rows x 1 columns],
 69:                      electric-combined
 time
 2017-01-04 09:00:00           0.459052
 2017-01-04 10:00:00           1.144033
 2017-01-04 11:00:00           2.221276
 2017-01-04 12:00:00           0.118737
 2017-01-04 13:00:00           0.732220
 ...                                ...
 2018-06-30 19:00:00           0.347951
 2018-06-30 20:00:00           0.495702
 2018-06-30 21:00:00           0.479640
 2018-06-30 22:00:00           0.391250
 2018-06-30 23:00:00           0.386478

 [13023 rows x 1 columns],
 75:                      electric-combined
 time
 2017-01-10 10:00:00           0.507754
 2017-01-10 11:00:00           0.518138
 2017-01-10 12:00:00           2.126506
 2017-01-10 13:00:00           0.182434
 2017-01-10 14:00:00           0.141756
 ...                                ...
 2018-06-14 05:00:00           0.077921
 2018-06-14 06:00:00           1.441470
 2018-06-14 07:00:00           0.463808
 2018-06-14 08:00:00           1.278061
 2018-06-14 09:00:00           0.056193

 [12480 rows x 1 columns],
 72:                      electric-combined
 time
 2017-01-04 13:00:00           0.007551
 2017-01-04 14:00:00           0.066044
 2017-01-04 15:00:00           0.091226
 2017-01-04 16:00:00           0.088904
 2017-01-04 17:00:00           0.090928
 ...                                ...
 2018-06-30 19:00:00           0.092530
 2018-06-30 20:00:00           0.092307
 2018-06-30 21:00:00           0.107918
 2018-06-30 22:00:00           0.111535
 2018-06-30 23:00:00           0.103916

 [13019 rows x 1 columns],
 74:                      electric-combined
 time
 2017-01-05 14:00:00           1.070466
 2017-01-05 15:00:00           0.768907
 2017-01-05 16:00:00           0.839558
 2017-01-05 17:00:00           0.790254
 2017-01-05 18:00:00           0.764438
 ...                                ...
 2018-06-30 19:00:00           0.424498
 2018-06-30 20:00:00           0.404584
 2018-06-30 21:00:00           0.415188
 2018-06-30 22:00:00           0.324067
 2018-06-30 23:00:00           0.221575

 [12994 rows x 1 columns],
 78:                      electric-combined
 time
 2017-01-19 09:00:00           0.210444
 2017-01-19 10:00:00           0.251651
 2017-01-19 11:00:00           0.235909
 2017-01-19 12:00:00           0.119740
 2017-01-19 13:00:00           0.256523
 ...                                ...
 2018-06-30 19:00:00           0.144765
 2018-06-30 20:00:00           0.204293
 2018-06-30 21:00:00           0.194197
 2018-06-30 22:00:00           0.124037
 2018-06-30 23:00:00           0.133053

 [12663 rows x 1 columns],
 71:                      electric-combined
 time
 2017-01-11 10:00:00           0.243211
 2017-01-11 11:00:00           0.239742
 2017-01-11 12:00:00           0.270739
 2017-01-11 13:00:00           0.222037
 2017-01-11 14:00:00           0.114646
 ...                                ...
 2018-06-30 19:00:00           0.209547
 2018-06-30 20:00:00           0.228465
 2018-06-30 21:00:00           0.333358
 2018-06-30 22:00:00           0.262725
 2018-06-30 23:00:00           0.192564

 [12854 rows x 1 columns],
 77:                      electric-combined
 time
 2017-01-17 09:00:00           0.180717
 2017-01-17 10:00:00           0.111414
 2017-01-17 11:00:00           0.068578
 2017-01-17 12:00:00           0.079192
 2017-01-17 13:00:00           0.056132
 ...                                ...
 2018-06-30 19:00:00           0.249974
 2018-06-30 20:00:00           0.100005
 2018-06-30 21:00:00           0.389471
 2018-06-30 22:00:00           0.959336
 2018-06-30 23:00:00           0.509145

 [12711 rows x 1 columns],
 76:                      electric-combined
 time
 2017-01-18 09:00:00           0.226291
 2017-01-18 10:00:00           0.326557
 2017-01-18 11:00:00           0.271034
 2017-01-18 12:00:00           0.552368
 2017-01-18 13:00:00           0.197523
 ...                                ...
 2018-06-30 19:00:00           0.207552
 2018-06-30 20:00:00           0.298912
 2018-06-30 21:00:00           0.314542
 2018-06-30 22:00:00           0.330788
 2018-06-30 23:00:00           0.332411

 [12687 rows x 1 columns],
 79:                      electric-combined
 time
 2016-11-04 13:00:00           0.021860
 2016-11-04 14:00:00           0.000000
 2016-11-04 15:00:00           0.000000
 2016-11-04 16:00:00           0.000000
 2016-11-04 17:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           0.199928
 2018-06-30 20:00:00           0.221741
 2018-06-30 21:00:00           0.283361
 2018-06-30 22:00:00           0.220756
 2018-06-30 23:00:00           0.228101

 [14483 rows x 1 columns],
 81:                      electric-combined
 time
 2017-01-26 13:00:00           0.010477
 2017-01-26 14:00:00           0.394649
 2017-01-26 15:00:00           0.267395
 2017-01-26 16:00:00           0.289096
 2017-01-26 17:00:00           0.987886
 ...                                ...
 2018-06-14 08:00:00           0.369922
 2018-06-14 09:00:00           0.169599
 2018-06-14 10:00:00           0.310449
 2018-06-14 11:00:00           0.240874
 2018-06-14 12:00:00           0.105037

 [12096 rows x 1 columns],
 88:                      electric-combined
 time
 2017-02-02 14:00:00           0.004912
 2017-02-02 15:00:00           0.330963
 2017-02-02 16:00:00           0.412140
 2017-02-02 17:00:00           0.536244
 2017-02-02 18:00:00           0.561438
 ...                                ...
 2018-02-25 17:00:00           0.212176
 2018-02-25 18:00:00           0.311447
 2018-02-25 19:00:00           0.252261
 2018-02-25 20:00:00           0.286604
 2018-02-25 21:00:00           0.118529

 [9320 rows x 1 columns],
 86:                      electric-combined
 time
 2017-02-02 11:00:00           0.284749
 2017-02-02 12:00:00           0.818082
 2017-02-02 13:00:00           0.295902
 2017-02-02 14:00:00           0.173254
 2017-02-02 15:00:00           0.156948
 ...                                ...
 2018-06-17 19:00:00           0.049069
 2018-06-17 20:00:00           0.479404
 2018-06-17 21:00:00           0.611478
 2018-06-17 22:00:00           0.191392
 2018-06-17 23:00:00           0.154933

 [12013 rows x 1 columns],
 83:                      electric-combined
 time
 2017-01-31 08:00:00           0.180676
 2017-01-31 09:00:00           0.480322
 2017-01-31 10:00:00           0.303106
 2017-01-31 11:00:00           0.392617
 2017-01-31 12:00:00           0.204982
 ...                                ...
 2018-06-10 05:00:00           0.193202
 2018-06-10 06:00:00           0.189942
 2018-06-10 07:00:00           0.763598
 2018-06-10 08:00:00           0.409674
 2018-06-10 09:00:00           0.029890

 [11882 rows x 1 columns],
 82:                      electric-combined
 time
 2016-10-25 14:00:00           0.006895
 2016-10-25 15:00:00           0.000000
 2016-10-25 16:00:00           0.000000
 2016-10-25 17:00:00           0.000000
 2016-10-25 18:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           1.362166
 2018-06-30 20:00:00           0.987463
 2018-06-30 21:00:00           0.569817
 2018-06-30 22:00:00           1.329794
 2018-06-30 23:00:00           0.538709

 [14722 rows x 1 columns],
 85:                      electric-combined
 time
 2017-02-02 08:00:00           0.038994
 2017-02-02 09:00:00           0.101202
 2017-02-02 10:00:00           0.142532
 2017-02-02 11:00:00           0.066247
 2017-02-02 12:00:00           0.058104
 ...                                ...
 2018-06-11 20:00:00           0.079359
 2018-06-11 21:00:00           0.114664
 2018-06-11 22:00:00           0.095229
 2018-06-11 23:00:00           0.088444
 2018-06-12 00:00:00           0.164574

 [11873 rows x 1 columns],
 89:                      electric-combined
 time
 2016-11-02 12:00:00           0.003177
 2016-11-02 13:00:00           0.000000
 2016-11-02 14:00:00           0.000000
 2016-11-02 15:00:00           0.000000
 2016-11-02 16:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           0.834688
 2018-06-30 20:00:00           0.692446
 2018-06-30 21:00:00           0.342025
 2018-06-30 22:00:00           0.210521
 2018-06-30 23:00:00           0.191064

 [14532 rows x 1 columns],
 90:                      electric-combined
 time
 2017-02-09 11:00:00           0.003352
 2017-02-09 12:00:00           0.055221
 2017-02-09 13:00:00           0.011489
 2017-02-09 14:00:00           0.000047
 2017-02-09 15:00:00           0.004995
 ...                                ...
 2018-06-30 19:00:00           0.202749
 2018-06-30 20:00:00           0.150825
 2018-06-30 21:00:00           0.117156
 2018-06-30 22:00:00           0.093892
 2018-06-30 23:00:00           0.037169

 [12157 rows x 1 columns],
 92:                      electric-combined
 time
 2017-02-14 11:00:00           0.156104
 2017-02-14 12:00:00           0.264994
 2017-02-14 13:00:00           0.198762
 2017-02-14 14:00:00           0.208520
 2017-02-14 15:00:00           0.208754
 ...                                ...
 2018-06-30 19:00:00           0.259563
 2018-06-30 20:00:00           0.418143
 2018-06-30 21:00:00           0.273469
 2018-06-30 22:00:00           0.231802
 2018-06-30 23:00:00           0.115798

 [12037 rows x 1 columns],
 93:                      electric-combined
 time
 2017-02-14 13:00:00           0.041725
 2017-02-14 14:00:00           0.192638
 2017-02-14 15:00:00           0.149223
 2017-02-14 16:00:00           0.166056
 2017-02-14 17:00:00           0.174216
 ...                                ...
 2018-06-28 03:00:00           0.065547
 2018-06-28 04:00:00           0.069779
 2018-06-28 05:00:00           0.067581
 2018-06-28 06:00:00           0.222838
 2018-06-28 07:00:00           0.069147

 [11971 rows x 1 columns],
 98:                      electric-combined
 time
 2017-03-02 11:00:00           0.022271
 2017-03-02 12:00:00           0.089582
 2017-03-02 13:00:00           0.045369
 2017-03-02 14:00:00           0.076297
 2017-03-02 15:00:00           0.104708
 ...                                ...
 2018-06-30 19:00:00           0.195811
 2018-06-30 20:00:00           0.222587
 2018-06-30 21:00:00           0.156843
 2018-06-30 22:00:00           0.057740
 2018-06-30 23:00:00           0.101622

 [11653 rows x 1 columns],
 94:                      electric-combined
 time
 2017-02-21 08:00:00           0.348851
 2017-02-21 09:00:00           0.309680
 2017-02-21 10:00:00           0.156426
 2017-02-21 11:00:00           0.104471
 2017-02-21 12:00:00           0.107504
 ...                                ...
 2018-06-30 19:00:00           0.664576
 2018-06-30 20:00:00           0.383714
 2018-06-30 21:00:00           0.199370
 2018-06-30 22:00:00           0.148579
 2018-06-30 23:00:00           0.062268

 [11872 rows x 1 columns],
 96:                      electric-combined
 time
 2017-02-28 10:00:00           0.265353
 2017-02-28 11:00:00           0.588963
 2017-02-28 12:00:00           0.433300
 2017-02-28 13:00:00           0.277778
 2017-02-28 14:00:00           0.333567
 ...                                ...
 2018-06-30 19:00:00           0.265739
 2018-06-30 20:00:00           0.221977
 2018-06-30 21:00:00           0.277015
 2018-06-30 22:00:00           0.256472
 2018-06-30 23:00:00           0.230392

 [11702 rows x 1 columns],
 97:                      electric-combined
 time
 2017-03-02 09:00:00           0.347915
 2017-03-02 10:00:00           0.775671
 2017-03-02 11:00:00           0.394309
 2017-03-02 12:00:00           0.431499
 2017-03-02 13:00:00           0.429560
 ...                                ...
 2018-05-13 06:00:00           0.593984
 2018-05-13 07:00:00           1.929082
 2018-05-13 08:00:00           0.341678
 2018-05-13 09:00:00           0.935581
 2018-05-13 10:00:00           0.445728

 [10490 rows x 1 columns],
 100:                      electric-combined
 time
 2017-03-07 14:00:00           0.106806
 2017-03-07 15:00:00           0.574898
 2017-03-07 16:00:00           0.484582
 2017-03-07 17:00:00           0.273006
 2017-03-07 18:00:00           0.182295
 ...                                ...
 2018-06-30 19:00:00           0.192080
 2018-06-30 20:00:00           0.232679
 2018-06-30 21:00:00           0.236639
 2018-06-30 22:00:00           0.213265
 2018-06-30 23:00:00           0.177600

 [11530 rows x 1 columns],
 101:                      electric-combined
 time
 2017-03-09 08:00:00           0.020294
 2017-03-09 09:00:00           0.101150
 2017-03-09 10:00:00           0.152022
 2017-03-09 11:00:00           0.092341
 2017-03-09 12:00:00           0.139811
 ...                                ...
 2018-06-26 09:00:00           0.054740
 2018-06-26 10:00:00           0.035850
 2018-06-26 11:00:00           0.060394
 2018-06-26 12:00:00           0.551802
 2018-06-26 13:00:00           0.327703

 [11382 rows x 1 columns],
 99:                      electric-combined
 time
 2017-03-07 08:00:00           0.013948
 2017-03-07 09:00:00           0.100609
 2017-03-07 10:00:00           0.144271
 2017-03-07 11:00:00           0.154736
 2017-03-07 12:00:00           0.187265
 ...                                ...
 2018-06-30 19:00:00           0.131068
 2018-06-30 20:00:00           0.103535
 2018-06-30 21:00:00           0.132442
 2018-06-30 22:00:00           0.095648
 2018-06-30 23:00:00           0.144348

 [11536 rows x 1 columns],
 102:                      electric-combined
 time
 2017-03-09 10:00:00           0.301273
 2017-03-09 11:00:00           0.492937
 2017-03-09 12:00:00           1.240941
 2017-03-09 13:00:00           0.377143
 2017-03-09 14:00:00           0.501164
 ...                                ...
 2018-06-12 03:00:00           0.129303
 2018-06-12 04:00:00           0.225983
 2018-06-12 05:00:00           0.201307
 2018-06-12 06:00:00           0.242106
 2018-06-12 07:00:00           0.153612

 [11038 rows x 1 columns],
 107:                      electric-combined
 time
 2017-04-04 13:00:00           0.400924
 2017-04-04 14:00:00           1.223255
 2017-04-04 15:00:00           0.822516
 2017-04-04 16:00:00           0.337210
 2017-04-04 17:00:00           0.071941
 ...                                ...

In [21]:
pickle.dump(data, open('D:/Documents/MSc Project/data/reduced_data.p', 'wb'))

In [22]:
df = pickle.load(open("D:/Documents/MSc Project/data/reduced_data.p", 'rb'))

In [23]:
df

{59:                      electric-combined
 time
 2016-10-06 09:00:00           0.135684
 2016-10-06 10:00:00           0.177023
 2016-10-06 11:00:00           0.587103
 2016-10-06 12:00:00           0.220286
 2016-10-06 13:00:00           0.143367
 ...                                ...
 2018-01-28 03:00:00           0.091263
 2018-01-28 04:00:00           0.077921
 2018-01-28 05:00:00           0.065573
 2018-01-28 06:00:00           0.061346
 2018-01-28 07:00:00           0.055258

 [11495 rows x 1 columns],
 61:                      electric-combined
 time
 2016-10-06 12:00:00           0.094648
 2016-10-06 13:00:00           0.215611
 2016-10-06 14:00:00           0.289798
 2016-10-06 15:00:00           0.078180
 2016-10-06 16:00:00           0.074056
 ...                                ...
 2017-10-19 02:00:00           0.054154
 2017-10-19 03:00:00           0.000000
 2017-10-19 04:00:00           0.174604
 2017-10-19 05:00:00           0.214912
 2017-10-19 06:00:00           0.285726

 [9067 rows x 1 columns],
 62:                      electric-combined
 time
 2016-08-26 09:00:00           0.015059
 2016-08-26 10:00:00           0.121332
 2016-08-26 11:00:00           0.272292
 2016-08-26 12:00:00           0.492458
 2016-08-26 13:00:00           0.541853
 ...                                ...
 2018-06-30 19:00:00           0.277313
 2018-06-30 20:00:00           0.221928
 2018-06-30 21:00:00           0.172749
 2018-06-30 22:00:00           0.163090
 2018-06-30 23:00:00           0.208072

 [16167 rows x 1 columns],
 64:                      electric-combined
 time
 2016-10-20 09:00:00           0.522627
 2016-10-20 10:00:00           0.257400
 2016-10-20 11:00:00           0.269574
 2016-10-20 12:00:00           0.167766
 2016-10-20 13:00:00           0.239859
 ...                                ...
 2018-06-30 19:00:00           0.209326
 2018-06-30 20:00:00           0.240710
 2018-06-30 21:00:00           0.149671
 2018-06-30 22:00:00           0.146466
 2018-06-30 23:00:00           0.146645

 [14847 rows x 1 columns],
 63:                      electric-combined
 time
 2016-10-28 13:00:00           0.233777
 2016-10-28 14:00:00           0.267790
 2016-10-28 15:00:00           0.243871
 2016-10-28 16:00:00           0.304959
 2016-10-28 17:00:00           0.178849
 ...                                ...
 2018-06-30 19:00:00           0.985282
 2018-06-30 20:00:00           0.474631
 2018-06-30 21:00:00           0.811795
 2018-06-30 22:00:00           0.697529
 2018-06-30 23:00:00           0.213694

 [14651 rows x 1 columns],
 65:                      electric-combined
 time
 2016-11-09 14:00:00           0.278701
 2016-11-09 15:00:00           0.655004
 2016-11-09 16:00:00           0.758222
 2016-11-09 17:00:00           0.482512
 2016-11-09 18:00:00           0.384276
 ...                                ...
 2018-06-30 19:00:00           1.085911
 2018-06-30 20:00:00           1.106592
 2018-06-30 21:00:00           0.475310
 2018-06-30 22:00:00           0.642547
 2018-06-30 23:00:00           1.436469

 [14362 rows x 1 columns],
 67:                      electric-combined
 time
 2016-12-05 10:00:00           0.146658
 2016-12-05 11:00:00           0.280612
 2016-12-05 12:00:00           1.850291
 2016-12-05 13:00:00           0.705230
 2016-12-05 14:00:00           0.356030
 ...                                ...
 2018-06-21 03:00:00           0.331729
 2018-06-21 04:00:00           0.279045
 2018-06-21 05:00:00           0.390250
 2018-06-21 06:00:00           0.183946
 2018-06-21 07:00:00           0.039205

 [13510 rows x 1 columns],
 66:                      electric-combined
 time
 2016-11-23 10:00:00           0.184380
 2016-11-23 11:00:00           0.291661
 2016-11-23 12:00:00           0.197729
 2016-11-23 13:00:00           0.164545
 2016-11-23 14:00:00           0.203255
 ...                                ...
 2018-06-30 19:00:00           0.185291
 2018-06-30 20:00:00           0.107985
 2018-06-30 21:00:00           0.138704
 2018-06-30 22:00:00           0.081042
 2018-06-30 23:00:00           0.127372

 [14030 rows x 1 columns],
 68:                      electric-combined
 time
 2016-11-24 10:00:00           0.334034
 2016-11-24 11:00:00           0.407336
 2016-11-24 12:00:00           0.367414
 2016-11-24 13:00:00           0.366431
 2016-11-24 14:00:00           0.280700
 ...                                ...
 2018-06-30 19:00:00           0.355875
 2018-06-30 20:00:00           0.475956
 2018-06-30 21:00:00           0.427902
 2018-06-30 22:00:00           0.305705
 2018-06-30 23:00:00           0.219891

 [14006 rows x 1 columns],
 70:                      electric-combined
 time
 2016-12-07 14:00:00           0.344933
 2016-12-07 15:00:00           0.622617
 2016-12-07 16:00:00           0.098561
 2016-12-07 17:00:00           0.117364
 2016-12-07 18:00:00           0.542610
 ...                                ...
 2018-06-30 19:00:00           0.090776
 2018-06-30 20:00:00           0.434951
 2018-06-30 21:00:00           0.766399
 2018-06-30 22:00:00           1.148596
 2018-06-30 23:00:00           0.919819

 [13690 rows x 1 columns],
 73:                      electric-combined
 time
 2016-12-15 14:00:00           0.000955
 2016-12-15 15:00:00           0.143301
 2016-12-15 16:00:00           0.069580
 2016-12-15 17:00:00           0.132617
 2016-12-15 18:00:00           0.267561
 ...                                ...
 2018-06-24 09:00:00           0.082796
 2018-06-24 10:00:00           0.150518
 2018-06-24 11:00:00           0.171477
 2018-06-24 12:00:00           0.733012
 2018-06-24 13:00:00           0.141034

 [13344 rows x 1 columns],
 69:                      electric-combined
 time
 2017-01-04 09:00:00           0.459052
 2017-01-04 10:00:00           1.144033
 2017-01-04 11:00:00           2.221276
 2017-01-04 12:00:00           0.118737
 2017-01-04 13:00:00           0.732220
 ...                                ...
 2018-06-30 19:00:00           0.347951
 2018-06-30 20:00:00           0.495702
 2018-06-30 21:00:00           0.479640
 2018-06-30 22:00:00           0.391250
 2018-06-30 23:00:00           0.386478

 [13023 rows x 1 columns],
 75:                      electric-combined
 time
 2017-01-10 10:00:00           0.507754
 2017-01-10 11:00:00           0.518138
 2017-01-10 12:00:00           2.126506
 2017-01-10 13:00:00           0.182434
 2017-01-10 14:00:00           0.141756
 ...                                ...
 2018-06-14 05:00:00           0.077921
 2018-06-14 06:00:00           1.441470
 2018-06-14 07:00:00           0.463808
 2018-06-14 08:00:00           1.278061
 2018-06-14 09:00:00           0.056193

 [12480 rows x 1 columns],
 72:                      electric-combined
 time
 2017-01-04 13:00:00           0.007551
 2017-01-04 14:00:00           0.066044
 2017-01-04 15:00:00           0.091226
 2017-01-04 16:00:00           0.088904
 2017-01-04 17:00:00           0.090928
 ...                                ...
 2018-06-30 19:00:00           0.092530
 2018-06-30 20:00:00           0.092307
 2018-06-30 21:00:00           0.107918
 2018-06-30 22:00:00           0.111535
 2018-06-30 23:00:00           0.103916

 [13019 rows x 1 columns],
 74:                      electric-combined
 time
 2017-01-05 14:00:00           1.070466
 2017-01-05 15:00:00           0.768907
 2017-01-05 16:00:00           0.839558
 2017-01-05 17:00:00           0.790254
 2017-01-05 18:00:00           0.764438
 ...                                ...
 2018-06-30 19:00:00           0.424498
 2018-06-30 20:00:00           0.404584
 2018-06-30 21:00:00           0.415188
 2018-06-30 22:00:00           0.324067
 2018-06-30 23:00:00           0.221575

 [12994 rows x 1 columns],
 78:                      electric-combined
 time
 2017-01-19 09:00:00           0.210444
 2017-01-19 10:00:00           0.251651
 2017-01-19 11:00:00           0.235909
 2017-01-19 12:00:00           0.119740
 2017-01-19 13:00:00           0.256523
 ...                                ...
 2018-06-30 19:00:00           0.144765
 2018-06-30 20:00:00           0.204293
 2018-06-30 21:00:00           0.194197
 2018-06-30 22:00:00           0.124037
 2018-06-30 23:00:00           0.133053

 [12663 rows x 1 columns],
 71:                      electric-combined
 time
 2017-01-11 10:00:00           0.243211
 2017-01-11 11:00:00           0.239742
 2017-01-11 12:00:00           0.270739
 2017-01-11 13:00:00           0.222037
 2017-01-11 14:00:00           0.114646
 ...                                ...
 2018-06-30 19:00:00           0.209547
 2018-06-30 20:00:00           0.228465
 2018-06-30 21:00:00           0.333358
 2018-06-30 22:00:00           0.262725
 2018-06-30 23:00:00           0.192564

 [12854 rows x 1 columns],
 77:                      electric-combined
 time
 2017-01-17 09:00:00           0.180717
 2017-01-17 10:00:00           0.111414
 2017-01-17 11:00:00           0.068578
 2017-01-17 12:00:00           0.079192
 2017-01-17 13:00:00           0.056132
 ...                                ...
 2018-06-30 19:00:00           0.249974
 2018-06-30 20:00:00           0.100005
 2018-06-30 21:00:00           0.389471
 2018-06-30 22:00:00           0.959336
 2018-06-30 23:00:00           0.509145

 [12711 rows x 1 columns],
 76:                      electric-combined
 time
 2017-01-18 09:00:00           0.226291
 2017-01-18 10:00:00           0.326557
 2017-01-18 11:00:00           0.271034
 2017-01-18 12:00:00           0.552368
 2017-01-18 13:00:00           0.197523
 ...                                ...
 2018-06-30 19:00:00           0.207552
 2018-06-30 20:00:00           0.298912
 2018-06-30 21:00:00           0.314542
 2018-06-30 22:00:00           0.330788
 2018-06-30 23:00:00           0.332411

 [12687 rows x 1 columns],
 79:                      electric-combined
 time
 2016-11-04 13:00:00           0.021860
 2016-11-04 14:00:00           0.000000
 2016-11-04 15:00:00           0.000000
 2016-11-04 16:00:00           0.000000
 2016-11-04 17:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           0.199928
 2018-06-30 20:00:00           0.221741
 2018-06-30 21:00:00           0.283361
 2018-06-30 22:00:00           0.220756
 2018-06-30 23:00:00           0.228101

 [14483 rows x 1 columns],
 81:                      electric-combined
 time
 2017-01-26 13:00:00           0.010477
 2017-01-26 14:00:00           0.394649
 2017-01-26 15:00:00           0.267395
 2017-01-26 16:00:00           0.289096
 2017-01-26 17:00:00           0.987886
 ...                                ...
 2018-06-14 08:00:00           0.369922
 2018-06-14 09:00:00           0.169599
 2018-06-14 10:00:00           0.310449
 2018-06-14 11:00:00           0.240874
 2018-06-14 12:00:00           0.105037

 [12096 rows x 1 columns],
 88:                      electric-combined
 time
 2017-02-02 14:00:00           0.004912
 2017-02-02 15:00:00           0.330963
 2017-02-02 16:00:00           0.412140
 2017-02-02 17:00:00           0.536244
 2017-02-02 18:00:00           0.561438
 ...                                ...
 2018-02-25 17:00:00           0.212176
 2018-02-25 18:00:00           0.311447
 2018-02-25 19:00:00           0.252261
 2018-02-25 20:00:00           0.286604
 2018-02-25 21:00:00           0.118529

 [9320 rows x 1 columns],
 86:                      electric-combined
 time
 2017-02-02 11:00:00           0.284749
 2017-02-02 12:00:00           0.818082
 2017-02-02 13:00:00           0.295902
 2017-02-02 14:00:00           0.173254
 2017-02-02 15:00:00           0.156948
 ...                                ...
 2018-06-17 19:00:00           0.049069
 2018-06-17 20:00:00           0.479404
 2018-06-17 21:00:00           0.611478
 2018-06-17 22:00:00           0.191392
 2018-06-17 23:00:00           0.154933

 [12013 rows x 1 columns],
 83:                      electric-combined
 time
 2017-01-31 08:00:00           0.180676
 2017-01-31 09:00:00           0.480322
 2017-01-31 10:00:00           0.303106
 2017-01-31 11:00:00           0.392617
 2017-01-31 12:00:00           0.204982
 ...                                ...
 2018-06-10 05:00:00           0.193202
 2018-06-10 06:00:00           0.189942
 2018-06-10 07:00:00           0.763598
 2018-06-10 08:00:00           0.409674
 2018-06-10 09:00:00           0.029890

 [11882 rows x 1 columns],
 82:                      electric-combined
 time
 2016-10-25 14:00:00           0.006895
 2016-10-25 15:00:00           0.000000
 2016-10-25 16:00:00           0.000000
 2016-10-25 17:00:00           0.000000
 2016-10-25 18:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           1.362166
 2018-06-30 20:00:00           0.987463
 2018-06-30 21:00:00           0.569817
 2018-06-30 22:00:00           1.329794
 2018-06-30 23:00:00           0.538709

 [14722 rows x 1 columns],
 85:                      electric-combined
 time
 2017-02-02 08:00:00           0.038994
 2017-02-02 09:00:00           0.101202
 2017-02-02 10:00:00           0.142532
 2017-02-02 11:00:00           0.066247
 2017-02-02 12:00:00           0.058104
 ...                                ...
 2018-06-11 20:00:00           0.079359
 2018-06-11 21:00:00           0.114664
 2018-06-11 22:00:00           0.095229
 2018-06-11 23:00:00           0.088444
 2018-06-12 00:00:00           0.164574

 [11873 rows x 1 columns],
 89:                      electric-combined
 time
 2016-11-02 12:00:00           0.003177
 2016-11-02 13:00:00           0.000000
 2016-11-02 14:00:00           0.000000
 2016-11-02 15:00:00           0.000000
 2016-11-02 16:00:00           0.000000
 ...                                ...
 2018-06-30 19:00:00           0.834688
 2018-06-30 20:00:00           0.692446
 2018-06-30 21:00:00           0.342025
 2018-06-30 22:00:00           0.210521
 2018-06-30 23:00:00           0.191064

 [14532 rows x 1 columns],
 90:                      electric-combined
 time
 2017-02-09 11:00:00           0.003352
 2017-02-09 12:00:00           0.055221
 2017-02-09 13:00:00           0.011489
 2017-02-09 14:00:00           0.000047
 2017-02-09 15:00:00           0.004995
 ...                                ...
 2018-06-30 19:00:00           0.202749
 2018-06-30 20:00:00           0.150825
 2018-06-30 21:00:00           0.117156
 2018-06-30 22:00:00           0.093892
 2018-06-30 23:00:00           0.037169

 [12157 rows x 1 columns],
 92:                      electric-combined
 time
 2017-02-14 11:00:00           0.156104
 2017-02-14 12:00:00           0.264994
 2017-02-14 13:00:00           0.198762
 2017-02-14 14:00:00           0.208520
 2017-02-14 15:00:00           0.208754
 ...                                ...
 2018-06-30 19:00:00           0.259563
 2018-06-30 20:00:00           0.418143
 2018-06-30 21:00:00           0.273469
 2018-06-30 22:00:00           0.231802
 2018-06-30 23:00:00           0.115798

 [12037 rows x 1 columns],
 93:                      electric-combined
 time
 2017-02-14 13:00:00           0.041725
 2017-02-14 14:00:00           0.192638
 2017-02-14 15:00:00           0.149223
 2017-02-14 16:00:00           0.166056
 2017-02-14 17:00:00           0.174216
 ...                                ...
 2018-06-28 03:00:00           0.065547
 2018-06-28 04:00:00           0.069779
 2018-06-28 05:00:00           0.067581
 2018-06-28 06:00:00           0.222838
 2018-06-28 07:00:00           0.069147

 [11971 rows x 1 columns],
 98:                      electric-combined
 time
 2017-03-02 11:00:00           0.022271
 2017-03-02 12:00:00           0.089582
 2017-03-02 13:00:00           0.045369
 2017-03-02 14:00:00           0.076297
 2017-03-02 15:00:00           0.104708
 ...                                ...
 2018-06-30 19:00:00           0.195811
 2018-06-30 20:00:00           0.222587
 2018-06-30 21:00:00           0.156843
 2018-06-30 22:00:00           0.057740
 2018-06-30 23:00:00           0.101622

 [11653 rows x 1 columns],
 94:                      electric-combined
 time
 2017-02-21 08:00:00           0.348851
 2017-02-21 09:00:00           0.309680
 2017-02-21 10:00:00           0.156426
 2017-02-21 11:00:00           0.104471
 2017-02-21 12:00:00           0.107504
 ...                                ...
 2018-06-30 19:00:00           0.664576
 2018-06-30 20:00:00           0.383714
 2018-06-30 21:00:00           0.199370
 2018-06-30 22:00:00           0.148579
 2018-06-30 23:00:00           0.062268

 [11872 rows x 1 columns],
 96:                      electric-combined
 time
 2017-02-28 10:00:00           0.265353
 2017-02-28 11:00:00           0.588963
 2017-02-28 12:00:00           0.433300
 2017-02-28 13:00:00           0.277778
 2017-02-28 14:00:00           0.333567
 ...                                ...
 2018-06-30 19:00:00           0.265739
 2018-06-30 20:00:00           0.221977
 2018-06-30 21:00:00           0.277015
 2018-06-30 22:00:00           0.256472
 2018-06-30 23:00:00           0.230392

 [11702 rows x 1 columns],
 97:                      electric-combined
 time
 2017-03-02 09:00:00           0.347915
 2017-03-02 10:00:00           0.775671
 2017-03-02 11:00:00           0.394309
 2017-03-02 12:00:00           0.431499
 2017-03-02 13:00:00           0.429560
 ...                                ...
 2018-05-13 06:00:00           0.593984
 2018-05-13 07:00:00           1.929082
 2018-05-13 08:00:00           0.341678
 2018-05-13 09:00:00           0.935581
 2018-05-13 10:00:00           0.445728

 [10490 rows x 1 columns],
 100:                      electric-combined
 time
 2017-03-07 14:00:00           0.106806
 2017-03-07 15:00:00           0.574898
 2017-03-07 16:00:00           0.484582
 2017-03-07 17:00:00           0.273006
 2017-03-07 18:00:00           0.182295
 ...                                ...
 2018-06-30 19:00:00           0.192080
 2018-06-30 20:00:00           0.232679
 2018-06-30 21:00:00           0.236639
 2018-06-30 22:00:00           0.213265
 2018-06-30 23:00:00           0.177600

 [11530 rows x 1 columns],
 101:                      electric-combined
 time
 2017-03-09 08:00:00           0.020294
 2017-03-09 09:00:00           0.101150
 2017-03-09 10:00:00           0.152022
 2017-03-09 11:00:00           0.092341
 2017-03-09 12:00:00           0.139811
 ...                                ...
 2018-06-26 09:00:00           0.054740
 2018-06-26 10:00:00           0.035850
 2018-06-26 11:00:00           0.060394
 2018-06-26 12:00:00           0.551802
 2018-06-26 13:00:00           0.327703

 [11382 rows x 1 columns],
 99:                      electric-combined
 time
 2017-03-07 08:00:00           0.013948
 2017-03-07 09:00:00           0.100609
 2017-03-07 10:00:00           0.144271
 2017-03-07 11:00:00           0.154736
 2017-03-07 12:00:00           0.187265
 ...                                ...
 2018-06-30 19:00:00           0.131068
 2018-06-30 20:00:00           0.103535
 2018-06-30 21:00:00           0.132442
 2018-06-30 22:00:00           0.095648
 2018-06-30 23:00:00           0.144348

 [11536 rows x 1 columns],
 102:                      electric-combined
 time
 2017-03-09 10:00:00           0.301273
 2017-03-09 11:00:00           0.492937
 2017-03-09 12:00:00           1.240941
 2017-03-09 13:00:00           0.377143
 2017-03-09 14:00:00           0.501164
 ...                                ...
 2018-06-12 03:00:00           0.129303
 2018-06-12 04:00:00           0.225983
 2018-06-12 05:00:00           0.201307
 2018-06-12 06:00:00           0.242106
 2018-06-12 07:00:00           0.153612

 [11038 rows x 1 columns],
 107:                      electric-combined
 time
 2017-04-04 13:00:00           0.400924
 2017-04-04 14:00:00           1.223255
 2017-04-04 15:00:00           0.822516
 2017-04-04 16:00:00           0.337210
 2017-04-04 17:00:00           0.071941
 ...                                ...

In [ ]:
def load_readings(houseid):
    'Funciton to load in data for the house electricity use'
    
    result = []
    
    data = ideal.get(homeid=houseid, subtype='electric-combined')[0]['readings']

    
    return data.size

In [ ]:
result = []

In [ ]:
for i in sample_homeids:
    
    size = load_readings(int(i))
    
    result.append(size)

In [ ]:
np.mean(result)

In [ ]:
sum(result)

In [ ]:
df = ideal.get(homeid=59, subtype='electric-combined')[0]['readings']

In [ ]:
df_copy = df.copy()

In [ ]:
temp = df_copy['2016-10-06 09:00:00':'2016-10-06 09:59:59']

In [ ]:
temp.mean()

In [ ]:
temp_hours = temp/3600

In [ ]:
temp_hours.sum()

In [ ]:
plt.hist(temp)

In [ ]:
plt.hist(temp_hours)

In [ ]:
test_df = pd.DataFrame(df_copy)

In [ ]:
test_df = test_df.resample('H').agg(lambda x: sum(x/3600)/1000)

In [ ]:
test_df

In [ ]:
test_df